# Generated by Django 4.0 on 2022-01-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTTK',
            fields=[
                ('tk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('cttk_hoten', models.CharField(max_length=250, null=True)),
                ('cttk_gioitinh', models.BooleanField(null=True)),
                ('cttk_ngaysinh', models.DateField(null=True)),
                ('cttk_sdt', models.CharField(max_length=11, null=True)),
                ('cttk_diachi', models.CharField(max_length=250, null=True)),
                ('cttk_avatar', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('danhmuc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('danhmuc_ten', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MGG',
            fields=[
                ('mgg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mgg_mgg', models.CharField(max_length=250)),
                ('mgg_giatri', models.FloatField()),
                ('mgg_thoihan', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('sp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sp_ten', models.CharField(max_length=250, null=True)),
                ('sp_mota', models.TextField(null=True)),
                ('sp_trangthai', models.CharField(default=0, max_length=20, null=True)),
                ('sp_luotxem', models.PositiveBigIntegerField(default=0)),
                ('sp_ngaytao', models.DateTimeField(auto_now_add=True)),
                ('sp_size', models.CharField(max_length=20, null=True)),
                ('sp_vi', models.CharField(max_length=20, null=True)),
                ('sp_soluong', models.PositiveSmallIntegerField(default=0)),
                ('sp_gia', models.DecimalField(decimal_places=2, max_digits=99)),
                ('danhmuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='HinhSP',
            fields=[
                ('hinhsp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hinhsp_url', models.ImageField(upload_to='')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('dh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dh_thoigian', models.DateTimeField(auto_now_add=True)),
                ('dh_thanhtoan', models.CharField(default=0, max_length=5)),
                ('dh_trangthai', models.CharField(default=0, max_length=5, null=True)),
                ('dh_tienhang', models.DecimalField(decimal_places=2, max_digits=99)),
                ('dh_ship', models.DecimalField(decimal_places=2, max_digits=99)),
                ('dh_giamgia', models.DecimalField(decimal_places=2, max_digits=99)),
                ('dh_tongtien', models.DecimalField(decimal_places=2, max_digits=99)),
                ('dh_hoten', models.CharField(max_length=250)),
                ('dh_sdt', models.CharField(max_length=11)),
                ('dh_diachi', models.CharField(max_length=250)),
                ('dh_email', models.EmailField(max_length=254, null=True)),
                ('tk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CTDH',
            fields=[
                ('ctdh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ctdh_tensp', models.CharField(max_length=250)),
                ('ctdh_vi', models.CharField(max_length=20)),
                ('ctdh_size', models.CharField(max_length=20)),
                ('ctdh_soluong', models.PositiveSmallIntegerField()),
                ('ctdh_gia', models.DecimalField(decimal_places=2, max_digits=99)),
                ('dh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.donhang')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sanpham')),
            ],
        ),
    ]
